### ISSUE TITLE
handle html-webpack-plugin template parameters

### ISSUE THREAD

**Issue by riw** [truerkarmy/nunjucks-template-loader#2]
hi
first of all: thx for your work!

would it be possible that you expose the html-webpack-plugin template parameters as variables in nunjucks?
(as e.g. the simple-nunjucks-loader already does but without the support for html-loader; plz see https://github.com/jantimon/html-webpack-plugin/tree/main/examples/custom-insertion-position for more detail)

**Comment by truerk** [comment]
> привет
> прежде всего: спасибо за вашу работу!
> 
> возможно ли, чтобы вы выставили параметры шаблона html-webpack-plugin как переменные в nunjucks?
> (например, простой-nunjucks-loader уже работает, но без поддержки html-loader; см. https://github.com/jantimon/html-webpack-plugin/tree/main/examples/custom-insertion-position для более детально)

hello riw, I'll see what can be done)

**Comment by truerkarmy** [comment]
> привет
> прежде всего: спасибо за вашу работу!
> 
> возможно ли, чтобы вы выставили параметры шаблона html-webpack-plugin как переменные в nunjucks?
> (например, простой-nunjucks-loader уже работает, но без поддержки html-loader; см. https://github.com/jantimon/html-webpack-plugin/tree/main/examples/custom-insertion-position для Подробнее)

В версии 3.0 добавлена переменная bundles:

```html

for css
{% for name, item in bundles.css %}
  <link rel="stylesheet" href="{{ item }}">
{% endfor %}
or 
<link rel="stylesheet" href="{{ bundles.css['entry_point_name'] }}">

for js
{% for name, item in bundles.js %}
   <script src="{{ item }}"></script>
{% endfor %}
or 
<script src="{{ bundles.js['entry_point_name'] }}"></script>
```
